spring:
  application:
    name: service-registry

  cloud:
    config:
      uri: http://localhost:9000  # Config Server URL

server:
  port: 9001  # Eureka server port

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    server:
      enable-self-preservation: false